version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    working_dir: /app

volumes:
  postgres-data:
